source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Midom' do
    pod 'Alamofire', '~> 4.4'
    pod 'Gloss', '~> 1.2'
    pod 'KeychainSwift', '~> 8.0'
    pod 'Timberjack'
    pod 'Toast-Swift', '~> 2.0.0'
end
